apiVersion: apps/v1
kind: Deployment
metadata:
  name: galera-ansible-operator
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      name: galera-ansible-operator
  template:
    metadata:
      labels:
        name: galera-ansible-operator
    spec:
      containers:
        - name: galera-ansible-operator
          image: docker-registry.default.svc:5000/test/galera-ansible-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
