apiVersion: apps/v1
kind: Deployment
metadata:
  name: galera-ansible-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: galera-ansible-operator
  template:
    metadata:
      labels:
        name: galera-ansible-operator
    spec:
      containers:
        - name: galera-ansible-operator
          image: gcr.io/consummate-atom-218703/galera-ansible-operator:latest
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
